# Generated by Django 4.0.5 on 2022-06-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_drink_category_name_drink_drink_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='drink_category',
        ),
        migrations.AddField(
            model_name='category',
            name='menu',
            field=models.ManyToManyField(to='product.drink'),
        ),
    ]
